"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRoyaltiesProvider__factory = void 0;
const ethers_1 = require("ethers");
class IRoyaltiesProvider__factory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IRoyaltiesProvider__factory = IRoyaltiesProvider__factory;
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "token",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "getRoyalties",
        outputs: [
            {
                components: [
                    {
                        internalType: "address payable",
                        name: "account",
                        type: "address",
                    },
                    {
                        internalType: "uint96",
                        name: "value",
                        type: "uint96",
                    },
                ],
                internalType: "struct LibPart.Part[]",
                name: "",
                type: "tuple[]",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
