"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MaliciousBidder__factory = void 0;
const ethers_1 = require("ethers");
class MaliciousBidder__factory extends ethers_1.ContractFactory {
    constructor(signer) {
        super(_abi, _bytecode, signer);
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.MaliciousBidder__factory = MaliciousBidder__factory;
const _abi = [
    {
        inputs: [
            {
                internalType: "contract IAuctionHouse",
                name: "auctionHouse",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "wizardId",
                type: "uint256",
            },
            {
                internalType: "uint8",
                name: "auctionId",
                type: "uint8",
            },
        ],
        name: "bid",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        stateMutability: "payable",
        type: "receive",
    },
];
const _bytecode = "0x608060405234801561001057600080fd5b5061016a806100206000396000f3fe6080604052600436106100225760003560e01c806398b349761461002e57600080fd5b3661002957fe5b600080fd5b61004161003c3660046100d3565b610043565b005b6040517fb7751c710000000000000000000000000000000000000000000000000000000081526004810183905260ff8216602482015273ffffffffffffffffffffffffffffffffffffffff84169063b7751c719034906044016000604051808303818588803b1580156100b557600080fd5b505af11580156100c9573d6000803e3d6000fd5b5050505050505050565b6000806000606084860312156100e857600080fd5b833573ffffffffffffffffffffffffffffffffffffffff8116811461010c57600080fd5b925060208401359150604084013560ff8116811461012957600080fd5b80915050925092509256fea26469706673582212200cf5a062cf24e73a6c968df2012251c036843b704aff6132b5ae92c67d6fe79064736f6c63430008060033";
