/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AuctionHouseInterface extends ethers.utils.Interface {
  functions: {
    "auctionCount()": FunctionFragment;
    "auctionOneOfOne()": FunctionFragment;
    "auctions(uint256)": FunctionFragment;
    "createBid(uint256,uint256)": FunctionFragment;
    "creatorFeePercent()": FunctionFragment;
    "creatorsDAO()": FunctionFragment;
    "daoWallet()": FunctionFragment;
    "duration()": FunctionFragment;
    "initialize(address,address,address,address,uint256,uint256,uint8,uint256,bool,uint256)": FunctionFragment;
    "lastWizardId()": FunctionFragment;
    "minBidIncrementPercentage()": FunctionFragment;
    "oneOfOneId()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "reachedCap()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reservePrice()": FunctionFragment;
    "setAuctionOneOfOne(bool)": FunctionFragment;
    "setCreatorsDAO(address)": FunctionFragment;
    "setDAOWallet(address)": FunctionFragment;
    "setMinBidIncrementPercentage(uint8)": FunctionFragment;
    "setOneOfOneId(uint48)": FunctionFragment;
    "setReservePrice(uint256)": FunctionFragment;
    "setTimeBuffer(uint256)": FunctionFragment;
    "setWhitelistAddresses(address[])": FunctionFragment;
    "setWizardCap(uint256)": FunctionFragment;
    "settleAuction(uint256)": FunctionFragment;
    "settleCurrentAndCreateNewAuction()": FunctionFragment;
    "stopWhitelistDay()": FunctionFragment;
    "timeBuffer()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "weth()": FunctionFragment;
    "whitelistAddrs(uint256)": FunctionFragment;
    "whitelistSize()": FunctionFragment;
    "wizardCap()": FunctionFragment;
    "wizards()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "auctionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctionOneOfOne",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorsDAO",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "daoWallet", values?: undefined): string;
  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lastWizardId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minBidIncrementPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oneOfOneId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reachedCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reservePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuctionOneOfOne",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorsDAO",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOWallet",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinBidIncrementPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOneOfOneId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReservePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimeBuffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistAddresses",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setWizardCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleCurrentAndCreateNewAuction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stopWhitelistDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeBuffer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelistAddrs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistSize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "wizardCap", values?: undefined): string;
  encodeFunctionData(functionFragment: "wizards", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "auctionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionOneOfOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorsDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daoWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastWizardId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minBidIncrementPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oneOfOneId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reachedCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuctionOneOfOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorsDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinBidIncrementPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOneOfOneId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimeBuffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWizardCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleCurrentAndCreateNewAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopWhitelistDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timeBuffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAddrs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wizardCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wizards", data: BytesLike): Result;

  events: {
    "AuctionBid(uint256,uint256,address,uint256,bool)": EventFragment;
    "AuctionCapReached(uint256)": EventFragment;
    "AuctionCapUpdated(uint256)": EventFragment;
    "AuctionCreated(uint256,uint256,uint256,uint256,bool,bool)": EventFragment;
    "AuctionExtended(uint256,uint256,uint256)": EventFragment;
    "AuctionMinBidIncrementPercentageUpdated(uint256)": EventFragment;
    "AuctionOneOfOne(bool)": EventFragment;
    "AuctionReservePriceUpdated(uint256)": EventFragment;
    "AuctionSettled(uint256,uint256,address,uint256)": EventFragment;
    "AuctionTimeBufferUpdated(uint256)": EventFragment;
    "CreatorsDAOUpdated(address)": EventFragment;
    "DAOWalletUpdated(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCapReached"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCapUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionExtended"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AuctionMinBidIncrementPercentageUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionOneOfOne"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionReservePriceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionTimeBufferUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatorsDAOUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAOWalletUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export class AuctionHouse extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AuctionHouseInterface;

  functions: {
    auctionCount(overrides?: CallOverrides): Promise<[number]>;

    "auctionCount()"(overrides?: CallOverrides): Promise<[number]>;

    auctionOneOfOne(overrides?: CallOverrides): Promise<[boolean]>;

    "auctionOneOfOne()"(overrides?: CallOverrides): Promise<[boolean]>;

    auctions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        wizardId: BigNumber;
        amount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        bidder: string;
        settled: boolean;
        isWhitelistDay: boolean;
      }
    >;

    "auctions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        wizardId: BigNumber;
        amount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        bidder: string;
        settled: boolean;
        isWhitelistDay: boolean;
      }
    >;

    createBid(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    creatorFeePercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    "creatorFeePercent()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    creatorsDAO(overrides?: CallOverrides): Promise<[string]>;

    "creatorsDAO()"(overrides?: CallOverrides): Promise<[string]>;

    daoWallet(overrides?: CallOverrides): Promise<[string]>;

    "daoWallet()"(overrides?: CallOverrides): Promise<[string]>;

    duration(overrides?: CallOverrides): Promise<[BigNumber]>;

    "duration()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(address,address,address,address,uint256,uint256,uint8,uint256,bool,uint256)"(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastWizardId(overrides?: CallOverrides): Promise<[BigNumber]>;

    "lastWizardId()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    minBidIncrementPercentage(overrides?: CallOverrides): Promise<[number]>;

    "minBidIncrementPercentage()"(overrides?: CallOverrides): Promise<[number]>;

    oneOfOneId(overrides?: CallOverrides): Promise<[number]>;

    "oneOfOneId()"(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    reachedCap(overrides?: CallOverrides): Promise<[boolean]>;

    "reachedCap()"(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    reservePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    "reservePrice()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    setAuctionOneOfOne(
      _auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAuctionOneOfOne(bool)"(
      _auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCreatorsDAO(
      _creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setCreatorsDAO(address)"(
      _creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOWallet(
      _daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setDAOWallet(address)"(
      _daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinBidIncrementPercentage(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMinBidIncrementPercentage(uint8)"(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setReservePrice(
      _reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setReservePrice(uint256)"(
      _reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTimeBuffer(
      _timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setTimeBuffer(uint256)"(
      _timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWizardCap(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleAuction(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleCurrentAndCreateNewAuction(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopWhitelistDay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "stopWhitelistDay()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timeBuffer(overrides?: CallOverrides): Promise<[BigNumber]>;

    "timeBuffer()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    "weth()"(overrides?: CallOverrides): Promise<[string]>;

    whitelistAddrs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "whitelistAddrs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    whitelistSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    "whitelistSize()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    wizardCap(overrides?: CallOverrides): Promise<[BigNumber]>;

    "wizardCap()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    wizards(overrides?: CallOverrides): Promise<[string]>;

    "wizards()"(overrides?: CallOverrides): Promise<[string]>;
  };

  auctionCount(overrides?: CallOverrides): Promise<number>;

  "auctionCount()"(overrides?: CallOverrides): Promise<number>;

  auctionOneOfOne(overrides?: CallOverrides): Promise<boolean>;

  "auctionOneOfOne()"(overrides?: CallOverrides): Promise<boolean>;

  auctions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
      wizardId: BigNumber;
      amount: BigNumber;
      startTime: BigNumber;
      endTime: BigNumber;
      bidder: string;
      settled: boolean;
      isWhitelistDay: boolean;
    }
  >;

  "auctions(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
      wizardId: BigNumber;
      amount: BigNumber;
      startTime: BigNumber;
      endTime: BigNumber;
      bidder: string;
      settled: boolean;
      isWhitelistDay: boolean;
    }
  >;

  createBid(
    wizardId: BigNumberish,
    aId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createBid(uint256,uint256)"(
    wizardId: BigNumberish,
    aId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  creatorFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

  "creatorFeePercent()"(overrides?: CallOverrides): Promise<BigNumber>;

  creatorsDAO(overrides?: CallOverrides): Promise<string>;

  "creatorsDAO()"(overrides?: CallOverrides): Promise<string>;

  daoWallet(overrides?: CallOverrides): Promise<string>;

  "daoWallet()"(overrides?: CallOverrides): Promise<string>;

  duration(overrides?: CallOverrides): Promise<BigNumber>;

  "duration()"(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _wizards: string,
    _creatorsDAO: string,
    _daoWallet: string,
    _weth: string,
    _timeBuffer: BigNumberish,
    _reservePrice: BigNumberish,
    _minBidIncrementPercentage: BigNumberish,
    _duration: BigNumberish,
    _auctionOneOfOne: boolean,
    _wizardCap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(address,address,address,address,uint256,uint256,uint8,uint256,bool,uint256)"(
    _wizards: string,
    _creatorsDAO: string,
    _daoWallet: string,
    _weth: string,
    _timeBuffer: BigNumberish,
    _reservePrice: BigNumberish,
    _minBidIncrementPercentage: BigNumberish,
    _duration: BigNumberish,
    _auctionOneOfOne: boolean,
    _wizardCap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastWizardId(overrides?: CallOverrides): Promise<BigNumber>;

  "lastWizardId()"(overrides?: CallOverrides): Promise<BigNumber>;

  minBidIncrementPercentage(overrides?: CallOverrides): Promise<number>;

  "minBidIncrementPercentage()"(overrides?: CallOverrides): Promise<number>;

  oneOfOneId(overrides?: CallOverrides): Promise<number>;

  "oneOfOneId()"(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  reachedCap(overrides?: CallOverrides): Promise<boolean>;

  "reachedCap()"(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceOwnership()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  reservePrice(overrides?: CallOverrides): Promise<BigNumber>;

  "reservePrice()"(overrides?: CallOverrides): Promise<BigNumber>;

  setAuctionOneOfOne(
    _auctionOneOfOne: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAuctionOneOfOne(bool)"(
    _auctionOneOfOne: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCreatorsDAO(
    _creatorsDAO: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setCreatorsDAO(address)"(
    _creatorsDAO: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOWallet(
    _daoWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setDAOWallet(address)"(
    _daoWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinBidIncrementPercentage(
    _minBidIncrementPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMinBidIncrementPercentage(uint8)"(
    _minBidIncrementPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOneOfOneId(
    _oneOfOneId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setOneOfOneId(uint48)"(
    _oneOfOneId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setReservePrice(
    _reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setReservePrice(uint256)"(
    _reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTimeBuffer(
    _timeBuffer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setTimeBuffer(uint256)"(
    _timeBuffer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWhitelistAddresses(
    _whitelistAddrs: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setWhitelistAddresses(address[])"(
    _whitelistAddrs: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWizardCap(
    _cap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setWizardCap(uint256)"(
    _cap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleAuction(
    aId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "settleAuction(uint256)"(
    aId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleCurrentAndCreateNewAuction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "settleCurrentAndCreateNewAuction()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopWhitelistDay(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "stopWhitelistDay()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timeBuffer(overrides?: CallOverrides): Promise<BigNumber>;

  "timeBuffer()"(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "unpause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  "weth()"(overrides?: CallOverrides): Promise<string>;

  whitelistAddrs(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "whitelistAddrs(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  whitelistSize(overrides?: CallOverrides): Promise<BigNumber>;

  "whitelistSize()"(overrides?: CallOverrides): Promise<BigNumber>;

  wizardCap(overrides?: CallOverrides): Promise<BigNumber>;

  "wizardCap()"(overrides?: CallOverrides): Promise<BigNumber>;

  wizards(overrides?: CallOverrides): Promise<string>;

  "wizards()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    auctionCount(overrides?: CallOverrides): Promise<number>;

    "auctionCount()"(overrides?: CallOverrides): Promise<number>;

    auctionOneOfOne(overrides?: CallOverrides): Promise<boolean>;

    "auctionOneOfOne()"(overrides?: CallOverrides): Promise<boolean>;

    auctions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        wizardId: BigNumber;
        amount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        bidder: string;
        settled: boolean;
        isWhitelistDay: boolean;
      }
    >;

    "auctions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        wizardId: BigNumber;
        amount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        bidder: string;
        settled: boolean;
        isWhitelistDay: boolean;
      }
    >;

    createBid(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    creatorFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    "creatorFeePercent()"(overrides?: CallOverrides): Promise<BigNumber>;

    creatorsDAO(overrides?: CallOverrides): Promise<string>;

    "creatorsDAO()"(overrides?: CallOverrides): Promise<string>;

    daoWallet(overrides?: CallOverrides): Promise<string>;

    "daoWallet()"(overrides?: CallOverrides): Promise<string>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    "duration()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address,address,uint256,uint256,uint8,uint256,bool,uint256)"(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    lastWizardId(overrides?: CallOverrides): Promise<BigNumber>;

    "lastWizardId()"(overrides?: CallOverrides): Promise<BigNumber>;

    minBidIncrementPercentage(overrides?: CallOverrides): Promise<number>;

    "minBidIncrementPercentage()"(overrides?: CallOverrides): Promise<number>;

    oneOfOneId(overrides?: CallOverrides): Promise<number>;

    "oneOfOneId()"(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    reachedCap(overrides?: CallOverrides): Promise<boolean>;

    "reachedCap()"(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    reservePrice(overrides?: CallOverrides): Promise<BigNumber>;

    "reservePrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    setAuctionOneOfOne(
      _auctionOneOfOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAuctionOneOfOne(bool)"(
      _auctionOneOfOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setCreatorsDAO(
      _creatorsDAO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCreatorsDAO(address)"(
      _creatorsDAO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDAOWallet(_daoWallet: string, overrides?: CallOverrides): Promise<void>;

    "setDAOWallet(address)"(
      _daoWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinBidIncrementPercentage(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMinBidIncrementPercentage(uint8)"(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setReservePrice(
      _reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setReservePrice(uint256)"(
      _reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTimeBuffer(
      _timeBuffer: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTimeBuffer(uint256)"(
      _timeBuffer: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setWizardCap(_cap: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleAuction(aId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleCurrentAndCreateNewAuction(overrides?: CallOverrides): Promise<void>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: CallOverrides
    ): Promise<void>;

    stopWhitelistDay(overrides?: CallOverrides): Promise<void>;

    "stopWhitelistDay()"(overrides?: CallOverrides): Promise<void>;

    timeBuffer(overrides?: CallOverrides): Promise<BigNumber>;

    "timeBuffer()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;

    "weth()"(overrides?: CallOverrides): Promise<string>;

    whitelistAddrs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "whitelistAddrs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    whitelistSize(overrides?: CallOverrides): Promise<BigNumber>;

    "whitelistSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    wizardCap(overrides?: CallOverrides): Promise<BigNumber>;

    "wizardCap()"(overrides?: CallOverrides): Promise<BigNumber>;

    wizards(overrides?: CallOverrides): Promise<string>;

    "wizards()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    AuctionBid(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      sender: null,
      value: null,
      extended: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber, boolean],
      {
        wizardId: BigNumber;
        aId: BigNumber;
        sender: string;
        value: BigNumber;
        extended: boolean;
      }
    >;

    AuctionCapReached(
      cap: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { cap: BigNumber }>;

    AuctionCapUpdated(
      cap: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { cap: BigNumber }>;

    AuctionCreated(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      startTime: null,
      endTime: null,
      oneOfOne: null,
      isWhitelistDay: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean, boolean],
      {
        wizardId: BigNumber;
        aId: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        oneOfOne: boolean;
        isWhitelistDay: boolean;
      }
    >;

    AuctionExtended(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      endTime: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { wizardId: BigNumber; aId: BigNumber; endTime: BigNumber }
    >;

    AuctionMinBidIncrementPercentageUpdated(
      minBidIncrementPercentage: null
    ): TypedEventFilter<[BigNumber], { minBidIncrementPercentage: BigNumber }>;

    AuctionOneOfOne(
      auctionOneOfOne: null
    ): TypedEventFilter<[boolean], { auctionOneOfOne: boolean }>;

    AuctionReservePriceUpdated(
      reservePrice: null
    ): TypedEventFilter<[BigNumber], { reservePrice: BigNumber }>;

    AuctionSettled(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      winner: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      { wizardId: BigNumber; aId: BigNumber; winner: string; amount: BigNumber }
    >;

    AuctionTimeBufferUpdated(
      timeBuffer: null
    ): TypedEventFilter<[BigNumber], { timeBuffer: BigNumber }>;

    CreatorsDAOUpdated(
      creatorsDAO: null
    ): TypedEventFilter<[string], { creatorsDAO: string }>;

    DAOWalletUpdated(
      daoWallet: null
    ): TypedEventFilter<[string], { daoWallet: string }>;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    Paused(account: null): TypedEventFilter<[string], { account: string }>;

    Unpaused(account: null): TypedEventFilter<[string], { account: string }>;
  };

  estimateGas: {
    auctionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "auctionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    auctionOneOfOne(overrides?: CallOverrides): Promise<BigNumber>;

    "auctionOneOfOne()"(overrides?: CallOverrides): Promise<BigNumber>;

    auctions(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "auctions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createBid(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    creatorFeePercent(overrides?: CallOverrides): Promise<BigNumber>;

    "creatorFeePercent()"(overrides?: CallOverrides): Promise<BigNumber>;

    creatorsDAO(overrides?: CallOverrides): Promise<BigNumber>;

    "creatorsDAO()"(overrides?: CallOverrides): Promise<BigNumber>;

    daoWallet(overrides?: CallOverrides): Promise<BigNumber>;

    "daoWallet()"(overrides?: CallOverrides): Promise<BigNumber>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    "duration()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(address,address,address,address,uint256,uint256,uint8,uint256,bool,uint256)"(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastWizardId(overrides?: CallOverrides): Promise<BigNumber>;

    "lastWizardId()"(overrides?: CallOverrides): Promise<BigNumber>;

    minBidIncrementPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    "minBidIncrementPercentage()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oneOfOneId(overrides?: CallOverrides): Promise<BigNumber>;

    "oneOfOneId()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    reachedCap(overrides?: CallOverrides): Promise<BigNumber>;

    "reachedCap()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    reservePrice(overrides?: CallOverrides): Promise<BigNumber>;

    "reservePrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    setAuctionOneOfOne(
      _auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAuctionOneOfOne(bool)"(
      _auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCreatorsDAO(
      _creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setCreatorsDAO(address)"(
      _creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOWallet(
      _daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setDAOWallet(address)"(
      _daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinBidIncrementPercentage(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMinBidIncrementPercentage(uint8)"(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setReservePrice(
      _reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setReservePrice(uint256)"(
      _reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTimeBuffer(
      _timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setTimeBuffer(uint256)"(
      _timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWizardCap(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleAuction(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleCurrentAndCreateNewAuction(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopWhitelistDay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "stopWhitelistDay()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timeBuffer(overrides?: CallOverrides): Promise<BigNumber>;

    "timeBuffer()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    "weth()"(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistAddrs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "whitelistAddrs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whitelistSize(overrides?: CallOverrides): Promise<BigNumber>;

    "whitelistSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    wizardCap(overrides?: CallOverrides): Promise<BigNumber>;

    "wizardCap()"(overrides?: CallOverrides): Promise<BigNumber>;

    wizards(overrides?: CallOverrides): Promise<BigNumber>;

    "wizards()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    auctionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "auctionCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    auctionOneOfOne(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "auctionOneOfOne()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    auctions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "auctions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createBid(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    creatorFeePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "creatorFeePercent()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    creatorsDAO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "creatorsDAO()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    daoWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "daoWallet()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    duration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "duration()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address,address,uint256,uint256,uint8,uint256,bool,uint256)"(
      _wizards: string,
      _creatorsDAO: string,
      _daoWallet: string,
      _weth: string,
      _timeBuffer: BigNumberish,
      _reservePrice: BigNumberish,
      _minBidIncrementPercentage: BigNumberish,
      _duration: BigNumberish,
      _auctionOneOfOne: boolean,
      _wizardCap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastWizardId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lastWizardId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minBidIncrementPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "minBidIncrementPercentage()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oneOfOneId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "oneOfOneId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reachedCap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "reachedCap()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    reservePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "reservePrice()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAuctionOneOfOne(
      _auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAuctionOneOfOne(bool)"(
      _auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCreatorsDAO(
      _creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setCreatorsDAO(address)"(
      _creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOWallet(
      _daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setDAOWallet(address)"(
      _daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinBidIncrementPercentage(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMinBidIncrementPercentage(uint8)"(
      _minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setReservePrice(
      _reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setReservePrice(uint256)"(
      _reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTimeBuffer(
      _timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setTimeBuffer(uint256)"(
      _timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWizardCap(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleAuction(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleCurrentAndCreateNewAuction(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopWhitelistDay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "stopWhitelistDay()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timeBuffer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "timeBuffer()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "weth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    whitelistAddrs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "whitelistAddrs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "whitelistSize()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wizardCap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "wizardCap()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wizards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "wizards()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
