/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IAuctionHouseInterface extends ethers.utils.Interface {
  functions: {
    "createBid(uint256,uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "setAuctionOneOfOne(bool)": FunctionFragment;
    "setCreatorsDAO(address)": FunctionFragment;
    "setDAOWallet(address)": FunctionFragment;
    "setMinBidIncrementPercentage(uint8)": FunctionFragment;
    "setOneOfOneId(uint48)": FunctionFragment;
    "setReservePrice(uint256)": FunctionFragment;
    "setTimeBuffer(uint256)": FunctionFragment;
    "setWhitelistAddresses(address[])": FunctionFragment;
    "setWizardCap(uint256)": FunctionFragment;
    "settleAuction(uint256)": FunctionFragment;
    "settleCurrentAndCreateNewAuction()": FunctionFragment;
    "stopWhitelistDay()": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuctionOneOfOne",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorsDAO",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOWallet",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinBidIncrementPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOneOfOneId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReservePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimeBuffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistAddresses",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setWizardCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleCurrentAndCreateNewAuction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stopWhitelistDay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "createBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuctionOneOfOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorsDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinBidIncrementPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOneOfOneId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimeBuffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWizardCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleCurrentAndCreateNewAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopWhitelistDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "AuctionBid(uint256,uint256,address,uint256,bool)": EventFragment;
    "AuctionCapReached(uint256)": EventFragment;
    "AuctionCapUpdated(uint256)": EventFragment;
    "AuctionCreated(uint256,uint256,uint256,uint256,bool,bool)": EventFragment;
    "AuctionExtended(uint256,uint256,uint256)": EventFragment;
    "AuctionMinBidIncrementPercentageUpdated(uint256)": EventFragment;
    "AuctionOneOfOne(bool)": EventFragment;
    "AuctionReservePriceUpdated(uint256)": EventFragment;
    "AuctionSettled(uint256,uint256,address,uint256)": EventFragment;
    "AuctionTimeBufferUpdated(uint256)": EventFragment;
    "CreatorsDAOUpdated(address)": EventFragment;
    "DAOWalletUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCapReached"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCapUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionExtended"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AuctionMinBidIncrementPercentageUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionOneOfOne"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionReservePriceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionTimeBufferUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatorsDAOUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAOWalletUpdated"): EventFragment;
}

export class IAuctionHouse extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAuctionHouseInterface;

  functions: {
    createBid(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuctionOneOfOne(
      auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAuctionOneOfOne(bool)"(
      auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCreatorsDAO(
      creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setCreatorsDAO(address)"(
      creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOWallet(
      daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setDAOWallet(address)"(
      daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinBidIncrementPercentage(
      minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMinBidIncrementPercentage(uint8)"(
      minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setReservePrice(
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setReservePrice(uint256)"(
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTimeBuffer(
      timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setTimeBuffer(uint256)"(
      timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWizardCap(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleAuction(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settleCurrentAndCreateNewAuction(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopWhitelistDay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "stopWhitelistDay()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createBid(
    wizardId: BigNumberish,
    aid: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createBid(uint256,uint256)"(
    wizardId: BigNumberish,
    aid: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuctionOneOfOne(
    auctionOneOfOne: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAuctionOneOfOne(bool)"(
    auctionOneOfOne: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCreatorsDAO(
    creatorsDAO: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setCreatorsDAO(address)"(
    creatorsDAO: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOWallet(
    daoWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setDAOWallet(address)"(
    daoWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinBidIncrementPercentage(
    minBidIncrementPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMinBidIncrementPercentage(uint8)"(
    minBidIncrementPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOneOfOneId(
    _oneOfOneId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setOneOfOneId(uint48)"(
    _oneOfOneId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setReservePrice(
    reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setReservePrice(uint256)"(
    reservePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTimeBuffer(
    timeBuffer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setTimeBuffer(uint256)"(
    timeBuffer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWhitelistAddresses(
    _whitelistAddrs: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setWhitelistAddresses(address[])"(
    _whitelistAddrs: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWizardCap(
    _cap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setWizardCap(uint256)"(
    _cap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleAuction(
    aId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "settleAuction(uint256)"(
    aId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settleCurrentAndCreateNewAuction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "settleCurrentAndCreateNewAuction()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopWhitelistDay(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "stopWhitelistDay()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "unpause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createBid(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    setAuctionOneOfOne(
      auctionOneOfOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAuctionOneOfOne(bool)"(
      auctionOneOfOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setCreatorsDAO(
      creatorsDAO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCreatorsDAO(address)"(
      creatorsDAO: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDAOWallet(daoWallet: string, overrides?: CallOverrides): Promise<void>;

    "setDAOWallet(address)"(
      daoWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinBidIncrementPercentage(
      minBidIncrementPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMinBidIncrementPercentage(uint8)"(
      minBidIncrementPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setReservePrice(
      reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setReservePrice(uint256)"(
      reservePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTimeBuffer(
      timeBuffer: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTimeBuffer(uint256)"(
      timeBuffer: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setWizardCap(_cap: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleAuction(aId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settleCurrentAndCreateNewAuction(overrides?: CallOverrides): Promise<void>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: CallOverrides
    ): Promise<void>;

    stopWhitelistDay(overrides?: CallOverrides): Promise<void>;

    "stopWhitelistDay()"(overrides?: CallOverrides): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    AuctionBid(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      sender: null,
      value: null,
      extended: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber, boolean],
      {
        wizardId: BigNumber;
        aId: BigNumber;
        sender: string;
        value: BigNumber;
        extended: boolean;
      }
    >;

    AuctionCapReached(
      cap: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { cap: BigNumber }>;

    AuctionCapUpdated(
      cap: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { cap: BigNumber }>;

    AuctionCreated(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      startTime: null,
      endTime: null,
      oneOfOne: null,
      isWhitelistDay: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean, boolean],
      {
        wizardId: BigNumber;
        aId: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        oneOfOne: boolean;
        isWhitelistDay: boolean;
      }
    >;

    AuctionExtended(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      endTime: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { wizardId: BigNumber; aId: BigNumber; endTime: BigNumber }
    >;

    AuctionMinBidIncrementPercentageUpdated(
      minBidIncrementPercentage: null
    ): TypedEventFilter<[BigNumber], { minBidIncrementPercentage: BigNumber }>;

    AuctionOneOfOne(
      auctionOneOfOne: null
    ): TypedEventFilter<[boolean], { auctionOneOfOne: boolean }>;

    AuctionReservePriceUpdated(
      reservePrice: null
    ): TypedEventFilter<[BigNumber], { reservePrice: BigNumber }>;

    AuctionSettled(
      wizardId: BigNumberish | null,
      aId: BigNumberish | null,
      winner: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      { wizardId: BigNumber; aId: BigNumber; winner: string; amount: BigNumber }
    >;

    AuctionTimeBufferUpdated(
      timeBuffer: null
    ): TypedEventFilter<[BigNumber], { timeBuffer: BigNumber }>;

    CreatorsDAOUpdated(
      creatorsDAO: null
    ): TypedEventFilter<[string], { creatorsDAO: string }>;

    DAOWalletUpdated(
      daoWallet: null
    ): TypedEventFilter<[string], { daoWallet: string }>;
  };

  estimateGas: {
    createBid(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuctionOneOfOne(
      auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAuctionOneOfOne(bool)"(
      auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCreatorsDAO(
      creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setCreatorsDAO(address)"(
      creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOWallet(
      daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setDAOWallet(address)"(
      daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinBidIncrementPercentage(
      minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMinBidIncrementPercentage(uint8)"(
      minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setReservePrice(
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setReservePrice(uint256)"(
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTimeBuffer(
      timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setTimeBuffer(uint256)"(
      timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWizardCap(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleAuction(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settleCurrentAndCreateNewAuction(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopWhitelistDay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "stopWhitelistDay()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createBid(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createBid(uint256,uint256)"(
      wizardId: BigNumberish,
      aid: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuctionOneOfOne(
      auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAuctionOneOfOne(bool)"(
      auctionOneOfOne: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCreatorsDAO(
      creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setCreatorsDAO(address)"(
      creatorsDAO: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOWallet(
      daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setDAOWallet(address)"(
      daoWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinBidIncrementPercentage(
      minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMinBidIncrementPercentage(uint8)"(
      minBidIncrementPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOneOfOneId(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setOneOfOneId(uint48)"(
      _oneOfOneId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setReservePrice(
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setReservePrice(uint256)"(
      reservePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTimeBuffer(
      timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setTimeBuffer(uint256)"(
      timeBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWhitelistAddresses(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setWhitelistAddresses(address[])"(
      _whitelistAddrs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWizardCap(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setWizardCap(uint256)"(
      _cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleAuction(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "settleAuction(uint256)"(
      aId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settleCurrentAndCreateNewAuction(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "settleCurrentAndCreateNewAuction()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopWhitelistDay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "stopWhitelistDay()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
